# Define the application build stage
FROM python:3.11.8-slim-bookworm AS build-stage

# Set work directory and environment variables
WORKDIR /crowdfund
ENV PYTHONDONTWRITEBYTECODE=1 \
  PYTHONBUFFERED=1

# Install & upgrade system dependencies
RUN apt-get update \
  && apt-get -y install netcat-openbsd gcc libpq-dev  \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Install project dependencies
COPY requirements.txt requirements-dev.txt /crowdfund/
RUN pip install --upgrade -r requirements.txt -r requirements-dev.txt

# Copy project
COPY . /crowdfund

# run_dev.sh
RUN ["chmod", "+x", "./run_dev.sh"]
CMD ["./run_dev.sh"]
