# fly.toml app configuration file generated for crowdfund-spring-pond-3303 on 2024-12-14T08:40:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crowdfund-spring-pond-3303'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[mounts]
  source = "crowdfund_data"
  destination = "/data"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
